### PR TITLE
updated DLLShoot to run the LL in parallel with ScoringActionHighHub, created DLLStop to end the command when the trigger is released

### PR DESCRIPTION
**Pull request by reevar24**
- DriveLimelight runs in parallel with: Scoring Prime, which stops when the robot is at the target distance, and ScoringActionHighHub, which is called after ScoringPrime is done
- added in a new DriveLimelightStop command to stop the motors 
- removed parameters from MoveWithLimelightIsFinished, so it could be used as a parallel command

### CODE REVIEW

**Review by cgjyang — APPROVED** [review]
Thanks for the writeup of all the changes, looks good!

**Review by frc2135 — COMMENTED** [review]
In DriveLimelightShoot think that DriveLimelight should not "endAtTarget" so it should pass a false in, and the ParallelRaceGroup on waiting for being at the target and ScoringPrime should be a deadline. Otherwise those will exit immediately and shoot where the robot is sitting.

**Comment by yabberyabber** [comment]
I see some deleted climber files. Were these deleted intentionally? Were they not used?

**Review by frc2135 — APPROVED** [review]
Looks good!

**Pull request merged**
