### PR TITLE
Removed unnecessary/unused climber grouped commands, increased gatehookRestHeight value to 1.85 inches

### PR DESCRIPTION
**Pull request by cgjyang**
Compiled, simulation ran, tested on robot

### CODE REVIEW

**Review by amull23 — COMMENTED** [review]
Question, why did we write the print, time, & inch return on separate lines in Climber.cpp?

**Comment by cgjyang** [comment]
> Question, why did we write the print, time, & inch return on separate lines in Climber.cpp?

I assume you’re talking abt lines 421-424 - it’s printing on one line, it just auto formatted the code to break the updated values we put into the print into separate lines- hopefully this makes sense!

**Review by amull23 — APPROVED** [review]
Thank you for clarifying, looks good!

**Review by ngupta-22 — APPROVED** [review]
Looks good!

**Pull request merged**
