### PR TITLE
Added climber sensor definitions

### PR DESCRIPTION
**Pull request by cgjyang**

### CODE REVIEW

**Review by jmullins16 — COMMENTED** [review]
We should not be declaring a new gyro here. There is only one on the robot, so we would need to access it through drivetrain subsystem for now. Please delete this declaration.

**Comment by cgjyang** [comment]
> 

just removed it, my bad

**Review by amull23 — APPROVED** [review]
looks good!

**Review by amull23 — APPROVED** [review]
looks good, thank you!

**Pull request merged**
