### PR TITLE
Updating the right trigger command

### PR DESCRIPTION
**Pull request by reevar24**

### CODE REVIEW

**Review by amull23 — APPROVED** [review]
looks good!

**Review by cgjyang — COMMENTED** [review]
Seems like there’s another rightTrigger object that is using the shooting high hub command below the line where you just added the new lines, not sure if that will interfere with the driveLimelightShoot cmd you just put in

We should test it on the robot before merging

**Comment by jmullins16** [comment]
Christine is correct. We confirmed this bug at practice field today. Please fix before merge.

**Review by ngupta-22 — APPROVED** [review]
Great job!

**Comment by cgjyang** [comment]
I think you've made really good progress with this so far! Just needs a little bit of debugging and tuning and it will work like a charm 👍

**Pull request merged**
