### PR TITLE
LL: added a method in Vision to change the display relative to if LL LED is on or off

### PR DESCRIPTION
**Pull request by reevar24**

### CODE REVIEW

**Comment by reevar24** [comment]
this has been tested and worked

**Review by ngupta-22 — APPROVED** [review]
Looks good! This will definitely make things easier for the drivers!

**Review by jmullins16 — COMMENTED** [review]
Fix log message in SetCamDisplay and also have constructor call SetCamDisplay with secondary PIP request.

**Review by ngupta-22 — APPROVED** [review]
Looks great!

**Review by jmullins16 — APPROVED** [review]
All great now! Good for merge.

**Pull request merged**
