### PR TITLE
Climber clean up and new drive slow mode for aligning to climb

### PR DESCRIPTION
**Pull request by cgjyang**
- I'll remove the reference to the drivetrain subsystem and add in initializing the variables for quickturn and driveslowmode in a next commit later

- tested on robot but teleop driving was not working

### CODE REVIEW

**Review by amull23 — APPROVED** [review]
looks good!

**Review by jmullins16 — APPROVED** [review]
Looks correct. Ready for testing in a robot.

**Review by reevar24 — APPROVED** [review]
looks good!

**Review by jmullins16 — APPROVED** [review]
Looks great and worked in testing!

**Pull request merged**
