### PR TITLE
Updated autonomous group commands: added new paths, modified sequencing, timeouts, and ScoringAction

### PR DESCRIPTION
**Pull request by ngupta-22**
- Added new paths (backwards79, offTarmac, ballToTarmac, and tarmacToBall) and removed old, unused paths
- Changed ShooterRun to never finish. Instead end this command externally when shooter is up to speed (in ScoringAction)
- Added timeout parameter for ScoringAction to control how long to shoot for (can be set for each ScoringAction instance in each group command)
- Added AutoStop in parallel with IntakeDeploy and ScoringAction in group commands that makes sure drive motors are fed at all times in these group commands
- Added debug configuration bool for ramsete tuning that sends velocity, position, and heading prints to SmartDashboard during RamseteFollowerExecute when true
- Tuned kP for autonomous velocity control
- Increased max velocity for auto paths to 2.5 m/s from 1.0 m/s
- Removed brake mode setting from RamseteFollowerInit and End

### CODE REVIEW

**Review by jmullins16 — COMMENTED** [review]
Overall looks good. There's quite a lot for people to review in one PR, so next time we should take this in much smaller pieces.

**Comment by yabberyabber** [comment]
Looks good to me. This pattern you have of making the command group responsible for ending the command is definitely an improvement.

**Review by amull23 — APPROVED** [review]
Looks good!

**Review by reevar24 — APPROVED** [review]
looks good👍

**Pull request merged**
