### PR TITLE
Added init() in constructors, reformatted DataLog calls, and defined variables globally 

### PR DESCRIPTION
**Pull request by reevar24**

### CODE REVIEW

**Review by amull23 — APPROVED** [review]
looks good!

**Review by jmullins16 — CHANGES_REQUESTED** [review]
Approve with one change. This line

DataLogManager.log(getSubsystem( ) + ": Chan is " + i + " & Current is" + powerDistribution.getCurrent(i));

I'm not sure what the & is for, and it needs a space after the last "is" so the number doesn't run together with it.

**Review by jmullins16 — APPROVED** [review]
Looks great!

**Comment by jmullins16** [comment]
Since approved by Alex and me, I'm merging this.

**Pull request merged**
