### PR TITLE
created ScoringActionLowHub/ScoringActionHighHub cpp and .h files.  Included ScoringActionLowHub in auto commands (will change after testing).  Gave new low hub and high hub rpm values in config file

### PR DESCRIPTION
**Pull request by amull23**

### CODE REVIEW

**Review by ngupta-22 — APPROVED** [review]
Looks good!

**Comment by reevar24** [comment]
looks good👍

**Review by reevar24 — APPROVED** [review]
looks good👍

**Review by cgjyang — APPROVED** [review]
Tested on comp bot and looked great!

**Pull request merged**
