### PR TITLE
Ported over Climber subsystem

### PR DESCRIPTION
**Pull request by reevar24**

### CODE REVIEW

**Review by jmullins16 — CHANGES_REQUESTED** [review]
Some minor change requests. I would lean toward getting another approval on this and have it merged in. However, it is not going to work yet from what I can see. I think that without the config file settings, it doesn't have enough of the motion magic info to work correctly.

**Review by hpark-24 — APPROVED** [review]
Looks amazing!

**Review by zaraansari17 — APPROVED** [review]
Looks amazing!!

**Review by jmullins16 — APPROVED** [review]
Looks great.

**Pull request merged**
