### PR TITLE
added isValid checks for all motors and rearranged shuffleboard Climber and Health Tab

### PR DESCRIPTION
**Pull request by amull23**

### CODE REVIEW

**Comment by amull23** [comment]
Screenshot (30)

**Comment by amull23** [comment]
Screenshot (29)

**Review by cgjyang — APPROVED** [review]
Layout looks good!

**Review by reevar24 — APPROVED** [review]
the new tab looks good!

**Review by jmullins16 — APPROVED** [review]
Approved as is, but valid checks on dashboard should be put written only in constructor--not initialize. And we'd like to have the resets for ALL motors in the health tab. Dashboard layout is pretty good, but it'd be nice to see the nine motors on one line and the nine resets below them. So we'll add a task to take this to the next level.

**Pull request merged**
