### PR TITLE
Ported teleop and config load methods to Drivetrain.java 

### PR DESCRIPTION
**Pull request by reevar24**

### CODE REVIEW

**Review by amull23 — COMMENTED** [review]
Overall, looks good.  However, I want to confirm that we switched to PigeonIMU and not Pigeon2 (I know you discussed that with Mr. Mullins, but I forgot what was decided).  Second, why did you remove the @Override periodic() method?

**Comment by jmullins16** [comment]
> Overall, looks good. However, I want to confirm that we switched to PigeonIMU and not Pigeon2 (I know you discussed that with Mr. Mullins, but I forgot what was decided). Second, why did you remove the @OverRide periodic() method?

First, great catch on deleting the @Override periodic--this is an error that needs to be fixed. It should come back into the code.

Second, our 2022 Comp robot has a PigeonIMU already installed, and the purpose of the Offseason2022 github project is to only port everything to Java.

When we start up the Swerve2022 github project (already created with empty files), we'll move to the Pigeon2 AND the CANivore module (and the RoboRIO2 from the benchtop board).

**Review by jmullins16 — CHANGES_REQUESTED** [review]
Don't port the RobotBuilder guards like this:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

We don't want them.

There are a couple of class variables that need to have the m_ prepended (now that we're doing it).

Looks like it might drive the robot if deployed, so that's good. We can look at the simulationPeriodic method next and maybe it'll drive on the field in simulation.

With those few changes above, this is good enough to approve and share with everyone. Great work!

**Review by amull23 — APPROVED** [review]
looks great!

**Review by jmullins16 — APPROVED** [review]
Looks good. Next approval can (and should) merge.

**Comment by jmullins16** [comment]
Looks like I was the second approval. Merging...

**Pull request merged**
