### PR TITLE
Falcon reset detection printed to Health Tab in smartdashboard for all motors

### PR DESCRIPTION
**Pull request by amull23**

### CODE REVIEW

**Review by cgjyang — APPROVED** [review]
Looks great! Hopefully we'll be able to use this to debug the CL motor issue :)

**Review by reevar24 — APPROVED** [review]
Looks good!

**Review by jmullins16 — COMMENTED** [review]
Good start. Right idea. Some comments that need addressed: 1) the HL_Resets_xx smartdashboard puts are in simulationPeriodic and not in Periodic where they should be. 2) the checks for FC8, IN6, SH11, VC9 should be saving those counts to member variables (not local variables). As is, all of those will only print the value 1 every time. DT is very close, though.

**Comment by amull23** [comment]
> Good start. Right idea. Some comments that need addressed: 1) the HL_Resets_xx smartdashboard puts are in simulationPeriodic and not in Periodic where they should be. 2) the checks for FC8, IN6, SH11, VC9 should be saving those counts to member variables (not local variables). As is, all of those will only print the value 1 every time. DT is very close, though.

I changed everything to member variables, but I thought that we wanted to place the smartdashboard puts in periodic and not in simulationPeriodic?

**Pull request merged**
