### PR TITLE
Debugging Swerve Drivetrain

### PR DESCRIPTION
**Pull request by hpark-24**

### CODE REVIEW

**Review by amull23 — COMMENTED** [review]
why is there no need to call m_swerve anymore?

**Comment by reevar24** [comment]
> why is there no need to call m_swerve anymore?

I think there was never a need to call it since we were accessing methods that we already in the file

**Review by reevar24 — APPROVED** [review]
🙂Looks good.

**Comment by amull23** [comment]
> > why is there no need to call m_swerve anymore?
> 
> I think there was never a need to call it since we were accessing methods that we already in the file

so true

**Review by amull23 — APPROVED** [review]
looks good!

**Pull request merged**
